---
steps:
  - name: "Construir documentação em formato HTML"
    description: "Documentação do projeto"
    plugin:
      name: "mkdocs_material"
      action: "build"

  - name: "Publicar HTML para github pages"
    ssh:
      copy_from: "${HOME}/.ssh"
    plugin:
      name: "git_publish"
      git_url: "git@github.com:geraldolsribeiro/microci_arc42.git"
      branch: "gh-pages"

  - name: "Servidor local na porta 8000 (Ctrl+C para finalizar)"
    description: "Executa servidor local para preview da documentação"
    only: "serve" # passo executado localmente para auxiliar na edição/preview
    network: host
    plugin:
      name: "mkdocs_material"
      action: "serve"
      port: 8000

# vim: spell spelllang=pt,en
