site_name: arc42 template documentation
repo_url: https://geraldolsribeiro.github.io/microci_arc42/
repo_name: geraldolsribeiro/microci_arc42
edit_uri: edit/master/docs/
remote_branch: gh-pages
remote_name: origin
site_description: arc42 template documentation
theme:
  name: material
  language: en
  logo: images/arc42-logo.png
  favicon: images/arc42-logo.png
  palette:
    primary: white
  icon:
    repo: fontawesome/brands/github
features:
  - navigation.instant
extra:
  homepage: https://geraldolsribeiro.github.io/microci_arc42/
extra_css:
  - css/print.css
markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
plugins:
  - search:
      lang: en
  - mermaid2
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
          site_name: microCI documentation template
        pt:
          name: Português
          build: true
          site_name: Modelo de documentação do microCI

# vim: spell spelllang=pt,en
